version: '3.9'
services:
  user_service:
    build:
      context: ./user_service
    ports:
      - "5005:5005"
  order_service:
    build:
      context: ./order_service
    ports:
      - "5001:5001"
  inventory_service:
    build:
      context: ./inventory_service
    ports:
      - "5002:5002"
  notification_service:
    build:
      context: ./notification_service
    ports:
      - "5003:5003"
  frontend_service:
    build:
      context: ./frontend_service
    ports:
      - "3000:3000"
  # load_test_service:
  #   build:
  #     context: ./load_test_service
  #   depends_on:
  #     - frontend_service
  #     - user_service
  #     - order_service
  #     - inventory_service
  #     - notification_service